# Generated by Django 5.1 on 2024-08-29 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreg',
            name='id',
        ),
        migrations.AddField(
            model_name='studentreg',
            name='student_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
