# Generated by Django 5.1 on 2024-08-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0002_remove_studentreg_id_studentreg_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreg',
            name='payment_plan',
            field=models.CharField(choices=[('full payment', 'Full Payment'), ('part payment', 'Part Payment')], default='full payment', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='type_of_training',
            field=models.CharField(choices=[('standard', 'Standard'), ('corporate', 'Corporate'), ('executive', 'Executive')], default='standard', max_length=50),
        ),
    ]
