# Generated by Django 5.1 on 2024-08-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0004_alter_studentreg_address_alter_studentreg_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreg',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='course_duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='hear_about_us',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='instructor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='next_of_kin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='occupation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='payment_plan',
            field=models.CharField(choices=[('full payment', 'Full Payment'), ('part payment', 'Part Payment')], default='full payment', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='registering_officer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='state_of_origin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='type_of_training',
            field=models.CharField(choices=[('standard', 'Standard'), ('corporate', 'Corporate'), ('executive', 'Executive')], default='standard', max_length=50),
        ),
    ]
