# Generated by Django 5.1 on 2024-08-30 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0005_alter_studentreg_address_alter_studentreg_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentreg',
            old_name='qualification',
            new_name='Qualification',
        ),
    ]
