# Generated by Django 5.1 on 2024-08-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0006_rename_qualification_studentreg_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreg',
            name='student_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
