# Generated by Django 5.1 on 2024-08-30 07:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0007_alter_studentreg_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreg',
            name='student_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
